Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/knl/dev/panopticon/panopticon/__main__.py", line 17, in <module>
    main()
  File "/home/knl/dev/panopticon/panopticon/__main__.py", line 14, in main
    print(ft.get_trace(), file=sys.stderr)
  File "/home/knl/dev/panopticon/panopticon/trace.py", line 23, in __str__
    "traceEvents": [asdict(x) for x in self._events],
  File "/home/knl/dev/panopticon/panopticon/trace.py", line 23, in <listcomp>
    "traceEvents": [asdict(x) for x in self._events],
  File "/usr/lib/python3.8/dataclasses.py", line 1073, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/usr/lib/python3.8/dataclasses.py", line 1081, in _asdict_inner
    result.append((f.name, value))
  File "/usr/lib/python3.8/dataclasses.py", line 1081, in _asdict_inner
    result.append((f.name, value))
  File "/home/knl/dev/panopticon/panopticon/tracer.py", line 64, in __call__
    print(frame, event, arg)
KeyboardInterrupt
